
import { GameDefinition, LevelConfig } from './types';

export const PRAISE_MESSAGES = ["Giỏi quá! 🌟", "Tuyệt vời luôn! 🌈", "Bé thông minh ghê! 🧠", "Xuất sắc! ✨", "Hoàn hảo luôn! 👏"];

/**
 * Factory function tạo Level nhanh chóng, chính xác
 */
const cL = (id: number, title: string, instr: string, cIcon: string, cLab: string, wIcon: string, wLab: string): LevelConfig => ({
  id,
  title: `Màn ${id}: ${title}`,
  instruction: instr,
  options: [
    { id: `${id}-c`, label: cLab, icon: cIcon, color: '#22C55E', isCorrect: true },
    { id: `${id}-w`, label: wLab, icon: wIcon, color: '#EF4444', isCorrect: false },
  ].sort(() => Math.random() - 0.5)
});

// --- NHÓM 1: TIẾNG ANH (15 Game: g1 -> g15) ---
const EnglishGames: GameDefinition[] = [
  { id: 'g1', category: 'English', title: 'Bé Học Alphabet A–E – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🅰️', themeColor: '#3B82F6', levels: [cL(1,"A","Find A","A","Apple","B","Ball"), cL(2,"B","Find B","B","Ball","C","Cat"), cL(3,"C","Find C","C","Cat","D","Dog"), cL(4,"D","Find D","D","Dog","E","Egg"), cL(5,"E","Find E","E","Egg","A","Ant")] },
  { id: 'g2', category: 'English', title: 'Bé Học Alphabet F–J – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🇫', themeColor: '#3B82F6', levels: [cL(1,"F","Find F","F","Fish","G","Goat"), cL(2,"G","Find G","G","Goat","H","Hat"), cL(3,"H","Find H","H","Hippo","I","Ice"), cL(4,"I","Find I","I","Ice","J","Jar"), cL(5,"J","Find J","J","Jar","F","Fish")] },
  { id: 'g3', category: 'English', title: 'Bé Học Alphabet K–O – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🇰', themeColor: '#3B82F6', levels: [cL(1,"K","Find K","K","Kite","L","Lion"), cL(2,"L","Find L","L","Lion","M","Moon"), cL(3,"M","Find M","M","Moon","N","Net"), cL(4,"N","Find N","N","Net","O","Owl"), cL(5,"O","Find O","O","Owl","K","Kite")] },
  { id: 'g4', category: 'English', title: 'Bé Học Alphabet P–T – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🇵', themeColor: '#3B82F6', levels: [cL(1,"P","Find P","P","Pig","Q","Queen"), cL(2,"Q","Find Q","Q","Queen","R","Rat"), cL(3,"R","Find R","R","Rat","S","Sun"), cL(4,"S","Find S","S","Sun","T","Tiger"), cL(5,"T","Find T","T","Tiger","P","Pig")] },
  { id: 'g5', category: 'English', title: 'Bé Học Alphabet U–Z – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🇺', themeColor: '#3B82F6', levels: [cL(1,"U","Find U","U","Up","V","Van"), cL(2,"V","Find V","V","Van","W","Watch"), cL(3,"W","Find W","W","Watch","X","Xmas"), cL(4,"X","Find X","X","Xmas","Y","Yo-yo"), cL(5,"Z","Find Z","Z","Zebra","U","Up")] },
  { id: 'g6', category: 'English', title: 'Bé Học Numbers 1–5 – Level Vui Nhộn 🧸', ageRange: '2-3 tuổi', icon: '1️⃣', themeColor: '#3B82F6', levels: [cL(1,"1","One","1","One","2","Two"), cL(2,"2","Two","2","Two","1","One"), cL(3,"3","Three","3","Three","4","Four"), cL(4,"4","Four","4","Four","5","Five"), cL(5,"5","Five","5","Five","1","One")] },
  { id: 'g7', category: 'English', title: 'Bé Học Numbers 6–10 – Level Vui Nhộn 🧸', ageRange: '3-4 tuổi', icon: '6️⃣', themeColor: '#3B82F6', levels: [cL(1,"6","Six","6","Six","7","Seven"), cL(2,"7","Seven","7","Seven","8","Eight"), cL(3,"8","Eight","8","Eight","9","Nine"), cL(4,"9","Nine","9","Nine","10","Ten"), cL(5,"10","Ten","10","Ten","6","Six")] },
  { id: 'g8', category: 'English', title: 'Bé Học Colors – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🌈', themeColor: '#3B82F6', levels: [cL(1,"Red","Find Red","🔴","Red","🔵","Blue"), cL(2,"Blue","Find Blue","🔵","Blue","🟡","Yellow"), cL(3,"Yellow","Find Yellow","🟡","Yellow","🟢","Green"), cL(4,"Green","Find Green","🟢","Green","🔴","Red"), cL(5,"Pink","Find Pink","🌸","Pink","⚫","Black")] },
  { id: 'g9', category: 'English', title: 'Bé Học Animals – Level Vui Nhộn 🧸', ageRange: '2-5 tuổi', icon: '🐶', themeColor: '#3B82F6', levels: [cL(1,"Dog","Dog","🐶","Dog","🐱","Cat"), cL(2,"Cat","Cat","🐱","Cat","🐷","Pig"), cL(3,"Pig","Pig","🐷","Pig","🐮","Cow"), cL(4,"Cow","Cow","🐮","Cow","🐶","Dog"), cL(5,"Duck","Duck","🦆","Duck","🐔","Hen")] },
  { id: 'g10', category: 'English', title: 'Bé Học Fruit – Level Vui Nhộn 🧸', ageRange: '2-5 tuổi', icon: '🍎', themeColor: '#3B82F6', levels: [cL(1,"Apple","Apple","🍎","Apple","🍌","Banana"), cL(2,"Banana","Banana","🍌","Banana","🍇","Grape"), cL(3,"Grape","Grape","🍇","Grape","🍓","Berry"), cL(4,"Berry","Berry","🍓","Berry","🍎","Apple"), cL(5,"Mango","Mango","🥭","Mango","🍐","Pear")] },
  { id: 'g11', category: 'English', title: 'Bé Học Shapes – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '📐', themeColor: '#3B82F6', levels: [cL(1,"Circle","Circle","⭕","Circle","⬜","Square"), cL(2,"Square","Square","⬜","Square","🔺","Triangle"), cL(3,"Triangle","Triangle","🔺","Triangle","⭐","Star"), cL(4,"Star","Star","⭐","Star","⭕","Circle"), cL(5,"Heart","Heart","❤️","Heart","⬜","Square")] },
  { id: 'g12', category: 'English', title: 'Bé Học Body Parts – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🧒', themeColor: '#3B82F6', levels: [cL(1,"Eyes","Eyes","👀","Eyes","👂","Ears"), cL(2,"Ears","Ears","👂","Ears","👃","Nose"), cL(3,"Nose","Nose","👃","Nose","👄","Mouth"), cL(4,"Mouth","Mouth","👄","Mouth","👀","Eyes"), cL(5,"Hand","Hand","✋","Hand","🦶","Foot")] },
  { id: 'g13', category: 'English', title: 'Bé Học Family – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '👨‍👩‍👧', themeColor: '#3B82F6', levels: [cL(1,"Dad","Father","👨","Dad","👩","Mom"), cL(2,"Mom","Mother","👩","Mom","👨","Dad"), cL(3,"Baby","Baby","👶","Baby","👵","Grandma"), cL(4,"Grandpa","Grandpa","👴","Grandpa","👨","Dad"), cL(5,"Grandma","Grandma","👵","Grandma","👶","Baby")] },
  { id: 'g14', category: 'English', title: 'Bé Học Actions – Level Vui Nhộn 🧸', ageRange: '4-6 tuổi', icon: '🏃', themeColor: '#3B82F6', levels: [cL(1,"Run","Running","🏃","Run","😴","Sleep"), cL(2,"Sleep","Sleeping","😴","Sleep","🏃","Run"), cL(3,"Eat","Eating","🍕","Eat","💧","Drink"), cL(4,"Jump","Jumping","🦘","Jump","🐢","Slow"), cL(5,"Sing","Singing","🎤","Sing","🏃","Run")] },
  { id: 'g15', category: 'English', title: 'Bé Học Nature – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🌳', themeColor: '#3B82F6', levels: [cL(1,"Sun","Sun","☀️","Sun","🌙","Moon"), cL(2,"Moon","Moon","🌙","Moon","☀️","Sun"), cL(3,"Tree","Tree","🌳","Tree","🌸","Flower"), cL(4,"Flower","Flower","🌸","Flower","🌳","Tree"), cL(5,"Rain","Rain","🌧️","Rain","☀️","Sun")] },
];

// --- NHÓM 2: TOÁN HỌC (15 Game: g16 -> g30) ---
const MathGames: GameDefinition[] = [
  { id: 'g16', category: 'Math', title: 'Bé Học Đếm 1–5 – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🔢', themeColor: '#10B981', levels: [cL(1,"1","Số 1","1","Một","2","Hai"), cL(2,"2","Số 2","2","Hai","3","Ba"), cL(3,"3","Số 3","3","Ba","1","Một"), cL(4,"4","Số 4","4","Bốn","5","Năm"), cL(5,"5","Số 5","5","Năm","2","Hai")] },
  { id: 'g17', category: 'Math', title: 'Bé Học Đếm 6–10 – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🔟', themeColor: '#10B981', levels: [cL(1,"6","Số 6","6","Sáu","5","Năm"), cL(2,"7","Số 7","7","Bảy","8","Tám"), cL(3,"8","Số 8","8","Tám","6","Sáu"), cL(4,"9","Số 9","9","Chín","10","Mười"), cL(5,"10","Số 10","10","Mười","1","Một")] },
  { id: 'g18', category: 'Math', title: 'Bé Tập So Sánh – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '⚖️', themeColor: '#10B981', levels: [cL(1,"To","Cái nào to hơn?","🐘","Voi","🐭","Chuột"), cL(2,"Nhỏ","Cái nào nhỏ hơn?","🐜","Kiến","🐻","Gấu"), cL(3,"Nhiều","Bên nào nhiều hơn?","🍎🍎","2 quả","🍎","1 quả"), cL(4,"Ít","Bên nào ít hơn?","⭐","1 sao","⭐⭐⭐","3 sao"), cL(5,"Dài","Cái nào dài hơn?","🐍","Rắn","🐛","Sâu")] },
  { id: 'g19', category: 'Math', title: 'Bé Làm Phép Cộng – Level Vui Nhộn 🧸', ageRange: '5-6 tuổi', icon: '➕', themeColor: '#10B981', levels: [cL(1,"1+1","1+1 bằng mấy?","2","Hai","1","Một"), cL(2,"2+1","2+1 bằng mấy?","3","Ba","4","Bốn"), cL(3,"3+2","3+2 bằng mấy?","5","Năm","4","Bốn"), cL(4,"2+2","2+2 bằng mấy?","4","Bốn","5","Năm"), cL(5,"4+1","4+1 bằng mấy?","5","Năm","3","Ba")] },
  { id: 'g20', category: 'Math', title: 'Bé Làm Phép Trừ – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '➖', themeColor: '#10B981', levels: [cL(1,"2-1","2-1 bằng mấy?","1","Một","2","Hai"), cL(2,"3-1","3-1 bằng mấy?","2","Hai","1","Một"), cL(3,"5-2","5-2 bằng mấy?","3","Ba","4","Bốn"), cL(4,"4-2","4-2 bằng mấy?","2","Hai","0","Không"), cL(5,"5-4","5-4 bằng mấy?","1","Một","5","Năm")] },
  { id: 'g21', category: 'Math', title: 'Bé Phân Loại Hình Khối – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🧊', themeColor: '#10B981', levels: [cL(1,"Tròn","Hình nào tròn?","⚽","Bóng","📦","Hộp"), cL(2,"Vuông","Hình nào vuông?","📦","Hộp","⚽","Bóng"), cL(3,"Tam giác","Hình nào giống tam giác?","🍕","Bánh Pizza","🍩","Bánh Donut"), cL(4,"Dài","Hình nào dài?","🥖","Bánh mì","🍪","Bánh quy"), cL(5,"Sao","Hình nào hình sao?","⭐","Ngôi sao","🌙","Mặt trăng")] },
  { id: 'g22', category: 'Math', title: 'Bé Học Đếm 11–20 – Level Vui Nhộn 🧸', ageRange: '5-6 tuổi', icon: '🔢', themeColor: '#10B981', levels: [cL(1,"11","Số 11","11","Mười một","12","Mười hai"), cL(2,"15","Số 15","15","Mười lăm","10","Mười"), cL(3,"20","Số 20","20","Hai mươi","19","Mười chín"), cL(4,"18","Số 18","18","Mười tám","16","Mười sáu"), cL(5,"13","Số 13","13","Mười ba","11","Mười một")] },
  { id: 'g23', category: 'Math', title: 'Bé Tìm Số Thiếu – Level Vui Nhộn 🧸', ageRange: '4-6 tuổi', icon: '❓', themeColor: '#10B981', levels: [cL(1,"1, ?, 3","Số nào ở giữa?","2","Số 2","4","Số 4"), cL(2,"4, 5, ?","Số tiếp theo là?","6","Số 6","3","Số 3"), cL(3,"?, 8, 9","Số đứng trước là?","7","Số 7","10","Số 10"), cL(4,"2, 4, ?","Đếm cách 2 đơn vị","6","Số 6","5","Số 5"), cL(5,"10, 9, ?","Đếm lùi","8","Số 8","11","Số 11")] },
  { id: 'g24', category: 'Math', title: 'Bé Học Về Thời Gian – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '⏰', themeColor: '#10B981', levels: [cL(1,"Sáng","Khi nào mặt trời mọc?","🌅","Buổi sáng","🌃","Buổi đêm"), cL(2,"Đêm","Khi nào đi ngủ?","🌃","Buổi đêm","☀️","Buổi trưa"), cL(3,"Đồng hồ","Cái nào xem giờ?","⌚","Đồng hồ","📱","Điện thoại"), cL(4,"Trưa","Ăn cơm trưa lúc?","☀️","Buổi trưa","🌅","Buổi sáng"), cL(5,"Thứ","Thứ mấy đi học?","📅","Thứ hai","🏖️","Chủ nhật")] },
  { id: 'g25', category: 'Math', title: 'Bé Học Tiền Tệ – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '💰', themeColor: '#10B981', levels: [cL(1,"Tiền","Cái nào dùng mua kẹo?","💵","Tiền giấy","🧻","Giấy vệ sinh"), cL(2,"Nhiều","Tờ nào giá trị hơn?","💯","Một trăm","🔟","Mười"), cL(3,"Ví","Tiền để ở đâu?","👛","Cái ví","🗑️","Thùng rác"), cL(4,"Heo đất","Tiết kiệm vào đâu?","🐖","Heo đất","🥣","Cái bát"), cL(5,"Mua","Tờ 5k mua được gì?","🍬","Kẹo","🚗","Ô tô")] },
  { id: 'g26', category: 'Math', title: 'Bé Tập Chia Phần – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🍰', themeColor: '#10B981', levels: [cL(1,"Một nửa","Chia đôi cái bánh","Half","Một nửa","Whole","Cả cái"), cL(2,"Nhiều","Phần nào to hơn?","Big","To","Small","Nhỏ"), cL(3,"Cả cái","Quả táo chưa cắt","Whole","Nguyên quả","Piece","Mảnh nhỏ"), cL(4,"4 phần","Cắt bánh làm 4","4","Bốn phần","2","Hai phần"), cL(5,"Mảnh","Ăn 1 mảnh nhỏ","Piece","Một mảnh","Box","Cả hộp")] },
  { id: 'g27', category: 'Math', title: 'Bé Học Về Vị Trí – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '📍', themeColor: '#10B981', levels: [cL(1,"Trên","Con chim ở đâu?","Trên","Trên cây","Dưới","Dưới đất"), cL(2,"Dưới","Con mèo ở đâu?","Dưới","Dưới gầm bàn","Trên","Trên bàn"), cL(3,"Trong","Quả táo ở đâu?","Trong","Trong giỏ","Ngoài","Ngoài sân"), cL(4,"Trái","Tay trái đâu?","Left","Bên trái","Right","Bên phải"), cL(5,"Phải","Tay phải đâu?","Right","Bên phải","Left","Bên trái")] },
  { id: 'g28', category: 'Math', title: 'Bé Tập Giải Toán Đố – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '💡', themeColor: '#10B981', levels: [cL(1,"Kẹo","Bé có 1 kẹo, mẹ cho 1. Có mấy?","2","Hai cái","1","Một cái"), cL(2,"Chim","3 chim, 1 bay đi. Còn mấy?","2","Hai con","3","Ba con"), cL(3,"Hoa","Bình có 2 hoa, thêm 3. Có mấy?","5","Năm bông","4","Bốn bông"), cL(4,"Bút","Có 5 bút, mất 2. Còn mấy?","3","Ba cái","5","Năm cái"), cL(5,"Táo","Ăn hết 1 quả táo. Còn mấy?","0","Hết rồi","1","Một quả")] },
  { id: 'g29', category: 'Math', title: 'Bé Nhận Biết Đo Lường – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '📏', themeColor: '#10B981', levels: [cL(1,"Nặng","Con nào nặng hơn?","🐘","Voi","🐜","Kiến"), cL(2,"Nhẹ","Cái nào nhẹ hơn?","🎈","Bóng bay","🧱","Viên gạch"), cL(3,"Cao","Bạn nào cao hơn?","🦒","Hươu cao cổ","🐕","Chó con"), cL(4,"Thấp","Cái nào thấp hơn?","🌱","Cỏ","🌳","Cây"), cL(5,"Đầy","Cốc nào đầy nước?","Full","Đầy","Empty","Cạn")] },
  { id: 'g30', category: 'Math', title: 'Bé Học Quy Luật (Pattern) – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🧩', themeColor: '#10B981', levels: [cL(1,"Đỏ-Xanh","Tiếp theo là gì? 🔴🔵🔴...","🔵","Xanh","🔴","Đỏ"), cL(2,"A-B","Tiếp theo là gì? ABAB...","A","Chữ A","B","Chữ B"), cL(3,"To-Nhỏ","Tiếp theo là gì? 🐘🐭🐘...","🐭","Chuột","🐘","Voi"), cL(4,"1-2","Tiếp theo là gì? 1212...","1","Số 1","2","Số 2"), cL(5,"Trăng-Sao","Tiếp theo là gì? 🌙⭐🌙...","⭐","Sao","🌙","Trăng")] },
];

// --- NHÓM 3: TIẾNG VIỆT (15 Game: g31 -> g45) ---
const VietnameseGames: GameDefinition[] = [
  { id: 'g31', category: 'Vietnamese', title: 'Bé Học Chữ A Ă Â – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🅰️', themeColor: '#EF4444', levels: [cL(1,"A","Tìm chữ A","A","Cá","B","Bò"), cL(2,"Ă","Tìm chữ Ă","Ă","Khăn","A","Ca"), cL(3,"Â","Tìm chữ Â","Â","Gấu","Ă","Khăn"), cL(4,"Dấu","Dấu nào dấu Sắc?","´","Sắc","`","Huyền"), cL(5,"Tổng hợp","Chữ nào là chữ Ă?","Ă","Đúng","A","Sai")] },
  { id: 'g32', category: 'Vietnamese', title: 'Bé Học Chữ B C D – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🅱️', themeColor: '#EF4444', levels: [cL(1,"B","Tìm chữ B","B","Bò","C","Cá"), cL(2,"C","Tìm chữ C","C","Cò","D","Dê"), cL(3,"D","Tìm chữ D","D","Dế","B","Bê"), cL(4,"Dấu","Dấu nào dấu Huyền?","`","Huyền","´","Sắc"), cL(5,"B-C","Con Cò bắt đầu bằng?","C","Cò","B","Bò")] },
  { id: 'g33', category: 'Vietnamese', title: 'Bé Học Chữ Đ E Ê – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇪', themeColor: '#EF4444', levels: [cL(1,"Đ","Tìm chữ Đ","Đ","Đàn","D","Dê"), cL(2,"E","Tìm chữ E","E","Xe","Ê","Lê"), cL(3,"Ê","Tìm chữ Ê","Ê","Dê","E","Xe"), cL(4,"Dấu","Dấu nào dấu Hỏi?","?","Hỏi","~","Ngã"), cL(5,"Đ-E","Con Đỉa bắt đầu bằng?","Đ","Đúng","D","Sai")] },
  { id: 'g34', category: 'Vietnamese', title: 'Bé Học Chữ G H I – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇬', themeColor: '#EF4444', levels: [cL(1,"G","Tìm chữ G","G","Gà","H","Hổ"), cL(2,"H","Tìm chữ H","H","Hoa","I","Bi"), cL(3,"I","Tìm chữ I","I","Bi","G","Gà"), cL(4,"Dấu","Dấu nào dấu Ngã?","~","Ngã","?","Hỏi"), cL(5,"G-H","Con Hổ bắt đầu bằng?","H","Đúng","G","Sai")] },
  { id: 'g35', category: 'Vietnamese', title: 'Bé Học Chữ K L M – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇰', themeColor: '#EF4444', levels: [cL(1,"K","Tìm chữ K","K","Kéo","L","Lá"), cL(2,"L","Tìm chữ L","L","Lá","M","Me"), cL(3,"M","Tìm chữ M","M","Mèo","K","Kéo"), cL(4,"Dấu","Dấu nào dấu Nặng?"," . ","Nặng","´","Sắc"), cL(5,"L-M","Cái Lá bắt đầu bằng?","L","Đúng","M","Sai")] },
  { id: 'g36', category: 'Vietnamese', title: 'Bé Học Chữ N O Ô – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🅾️', themeColor: '#EF4444', levels: [cL(1,"N","Tìm chữ N","N","Nấm","M","Me"), cL(2,"O","Tìm chữ O","O","Bò","Ô","Hổ"), cL(3,"Ô","Tìm chữ Ô","Ô","Hổ","O","Bò"), cL(4,"Vòng","Chữ nào có mũ?","Ô","Đúng","O","Sai"), cL(5,"N-O","Quả Nho bắt đầu bằng?","N","Đúng","M","Sai")] },
  { id: 'g37', category: 'Vietnamese', title: 'Bé Học Chữ Ơ P Q – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇶', themeColor: '#EF4444', levels: [cL(1,"Ơ","Tìm chữ Ơ","Ơ","Cờ","O","Bò"), cL(2,"P","Tìm chữ P","P","Pin","B","Bò"), cL(3,"Q","Tìm chữ Q","Q","Quà","K","Kéo"), cL(4,"Móc","Chữ nào có râu?","Ơ","Đúng","O","Sai"), cL(5,"Q-P","Món Quà bắt đầu bằng?","Q","Đúng","K","Sai")] },
  { id: 'g38', category: 'Vietnamese', title: 'Bé Học Chữ R S T – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇷', themeColor: '#EF4444', levels: [cL(1,"R","Tìm chữ R","R","Rùa","S","Sóc"), cL(2,"S","Tìm chữ S","S","Sóc","T","Tôm"), cL(3,"T","Tìm chữ T","T","Tôm","R","Rùa"), cL(4,"Đầu","Con Sóc bắt đầu bằng?","S","Đúng","X","Sai"), cL(5,"T-R","Con Rùa bắt đầu bằng?","R","Đúng","T","Sai")] },
  { id: 'g39', category: 'Vietnamese', title: 'Bé Học Chữ U Ư V – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇻', themeColor: '#EF4444', levels: [cL(1,"U","Tìm chữ U","U","Đu","Ư","Sư"), cL(2,"Ư","Tìm chữ Ư","Ư","Sư","U","Đu"), cL(3,"V","Tìm chữ V","V","Voi","U","Đu"), cL(4,"Móc","Chữ nào có râu?","Ư","Đúng","U","Sai"), cL(5,"V-U","Con Voi bắt đầu bằng?","V","Đúng","D","Sai")] },
  { id: 'g40', category: 'Vietnamese', title: 'Bé Học Chữ X Y – Level Vui Nhộn 🧸', ageRange: '4-5 tuổi', icon: '🇾', themeColor: '#EF4444', levels: [cL(1,"X","Tìm chữ X","X","Xe","S","Sóc"), cL(2,"Y","Tìm chữ Y","Y","Y tế","I","Bi"), cL(3,"Dấu","Chữ nào là chữ X?","X","Đúng","S","Sai"), cL(4,"Cuối","Chữ cuối bảng chữ cái?","Y","Đúng","A","Sai"), cL(5,"X-Y","Xe cộ bắt đầu bằng?","X","Đúng","S","Sai")] },
  { id: 'g41', category: 'Vietnamese', title: 'Bé Học Ghép Vần BA CA – Level Vui Nhộn 🧸', ageRange: '5-6 tuổi', icon: '🧱', themeColor: '#EF4444', levels: [cL(1,"BA","B-A đọc là gì?","BA","Ba","BO","Bo"), cL(2,"CA","C-A đọc là gì?","CA","Ca","CU","Cu"), cL(3,"CÁ","C-A-Sắc đọc là?","CÁ","Cá","CÀ","Cà"), cL(4,"BÀ","B-A-Huyền đọc là?","BÀ","Bà","BÁ","Bá"), cL(5,"BỐ","B-Ô-Sắc đọc là?","BỐ","Bố","BỘ","Bộ")] },
  { id: 'g42', category: 'Vietnamese', title: 'Bé Học Vần Mẹ Bé – Level Vui Nhộn 🧸', ageRange: '5-6 tuổi', icon: '🤱', themeColor: '#EF4444', levels: [cL(1,"MẸ","M-E-Nặng đọc là?","MẸ","Mẹ","ME","Me"), cL(2,"BÉ","B-E-Sắc đọc là?","BÉ","Bé","BE","Be"), cL(3,"GÀ","G-A-Huyền đọc là?","GÀ","Gà","GA","Ga"), cL(4,"CÒ","C-O-Huyền đọc là?","CÒ","Cò","CO","Co"), cL(5,"DÊ","D-Ê đọc là?","DÊ","Dê","DE","De")] },
  { id: 'g43', category: 'Vietnamese', title: 'Bé Đọc Từ Đơn – Level Vui Nhộn 🧸', ageRange: '5-6 tuổi', icon: '📖', themeColor: '#EF4444', levels: [cL(1,"Nhà","Chữ nào là chữ NHÀ?","Nhà","Đúng","Lá","Sai"), cL(2,"Hoa","Chữ nào là chữ HOA?","Hoa","Đúng","Quả","Sai"), cL(3,"Lá","Chữ nào là chữ LÁ?","Lá","Đúng","Cành","Sai"), cL(4,"Quả","Chữ nào là chữ QUẢ?","Quả","Đúng","Hoa","Sai"), cL(5,"Cá","Chữ nào là chữ CÁ?","Cá","Đúng","Bò","Sai")] },
  { id: 'g44', category: 'Vietnamese', title: 'Bé Học Dấu Câu – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '✍️', themeColor: '#EF4444', levels: [cL(1,"Sắc","Dấu Sắc đặt ở đâu?","´","Sắc","`","Huyền"), cL(2,"Huyền","Dấu Huyền đặt ở đâu?","`","Huyền","´","Sắc"), cL(3,"Hỏi","Dấu Hỏi đâu bé?","?","Hỏi","~","Ngã"), cL(4,"Ngã","Dấu Ngã đâu bé?","~","Ngã","?","Hỏi"), cL(5,"Nặng","Dấu Nặng đâu bé?"," . ","Nặng","´","Sắc")] },
  { id: 'g45', category: 'Vietnamese', title: 'Bé Tập Đọc Câu Ngắn – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '📝', themeColor: '#EF4444', levels: [cL(1,"Bé đi học","Bé đi đâu?","Trường","Đi học","Sân","Đi chơi"), cL(2,"Mẹ yêu bé","Mẹ yêu ai?","Bé","Đúng","Ba","Sai"), cL(3,"Cá bơi","Cá làm gì?","Bơi","Đúng","Bay","Sai"), cL(4,"Gà gáy","Gà kêu thế nào?","Ò ó o","Đúng","Meo meo","Sai"), cL(5,"Bé ngoan","Bé thế nào?","Ngoan","Đúng","Hư","Sai")] },
];

// --- NHÓM 4: GHI NHỚ (10 Game: g46 -> g55) ---
const MemoryGames: GameDefinition[] = [
  { id: 'g46', category: 'Logic', title: 'Lật Hình Chữ Cái Anh Ngữ – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🃏', themeColor: '#8B5CF6', levels: [cL(1,"A","Nhớ chữ A trốn đâu?","A","Đúng","B","Sai"), cL(2,"B","Nhớ chữ B trốn đâu?","B","Đúng","C","Sai"), cL(3,"C","Nhớ chữ C trốn đâu?","C","Đúng","D","Sai"), cL(4,"D","Nhớ chữ D trốn đâu?","D","Đúng","A","Sai"), cL(5,"E","Nhớ chữ E trốn đâu?","E","Đúng","F","Sai")] },
  { id: 'g47', category: 'Logic', title: 'Lật Hình Số Đếm 1–10 – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🔢', themeColor: '#8B5CF6', levels: [cL(1,"1","Nhớ số 1","1","Đúng","2","Sai"), cL(2,"5","Nhớ số 5","5","Đúng","4","Sai"), cL(3,"8","Nhớ số 8","8","Đúng","9","Sai"), cL(4,"3","Nhớ số 3","3","Đúng","6","Sai"), cL(5,"10","Nhớ số 10","10","Đúng","1","Sai")] },
  { id: 'g48', category: 'Logic', title: 'Lật Hình Con Vật Quen Thuộc – Level Vui Nhộn 🧸', ageRange: '2-5 tuổi', icon: '🐶', themeColor: '#8B5CF6', levels: [cL(1,"Chó","Nhớ bạn chó","🐶","Đúng","🐱","Sai"), cL(2,"Mèo","Nhớ bạn mèo","🐱","Đúng","🐭","Sai"), cL(3,"Voi","Nhớ bạn voi","🐘","Đúng","🦒","Sai"), cL(4,"Khỉ","Nhớ bạn khỉ","🐒","Đúng","🦁","Sai"), cL(5,"Sư tử","Nhớ sư tử","🦁","Đúng","🐷","Sai")] },
  { id: 'g49', category: 'Logic', title: 'Lật Hình Hoa Quả Tươi – Level Vui Nhộn 🧸', ageRange: '2-5 tuổi', icon: '🍎', themeColor: '#8B5CF6', levels: [cL(1,"Táo","Nhớ quả táo","🍎","Đúng","🍌","Sai"), cL(2,"Chuối","Nhớ quả chuối","🍌","Đúng","🍇","Sai"), cL(3,"Nho","Nhớ chùm nho","🍇","Đúng","🍓","Sai"), cL(4,"Dâu","Nhớ quả dâu","🍓","Đúng","🍎","Sai"), cL(5,"Cam","Nhớ quả cam","🍊","Đúng","🍋","Sai")] },
  { id: 'g50', category: 'Logic', title: 'Lật Hình Màu Sắc – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🔴', themeColor: '#8B5CF6', levels: [cL(1,"Đỏ","Nhớ màu đỏ","🔴","Đỏ","🔵","Xanh"), cL(2,"Xanh","Nhớ màu xanh","🔵","Xanh","🟡","Vàng"), cL(3,"Vàng","Nhớ màu vàng","🟡","Vàng","🟢","Lá"), cL(4,"Lá","Nhớ màu lá","🟢","Lá","🔴","Đỏ"), cL(5,"Tím","Nhớ màu tím","🟣","Tím","⬛","Đen")] },
  { id: 'g51', category: 'Logic', title: 'Lật Hình Đồ Vật Trong Nhà – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🏠', themeColor: '#8B5CF6', levels: [cL(1,"Giường","Nhớ cái giường","🛏️","Đúng","🛋️","Sai"), cL(2,"Ghế","Nhớ cái ghế","🛋️","Đúng","🛏️","Sai"), cL(3,"Bát","Nhớ cái bát","🥣","Đúng","🥄","Sai"), cL(4,"Thìa","Nhớ cái thìa","🥄","Đúng","🥣","Sai"), cL(5,"Tủ","Nhớ cái tủ","🗄️","Đúng","🏠","Sai")] },
  { id: 'g52', category: 'Logic', title: 'Lật Hình Giao Thông – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🚗', themeColor: '#8B5CF6', levels: [cL(1,"Ô tô","Nhớ ô tô","🚗","Đúng","🚲","Sai"), cL(2,"Xe đạp","Nhớ xe đạp","🚲","Đúng","🚗","Sai"), cL(3,"Máy bay","Nhớ máy bay","✈️","Đúng","🚢","Sai"), cL(4,"Tàu thủy","Nhớ tàu thủy","🚢","Đúng","✈️","Sai"), cL(5,"Xe buýt","Nhớ xe buýt","🚌","Đúng","🚁","Sai")] },
  { id: 'g53', category: 'Logic', title: 'Lật Hình Chữ Việt – Level Vui Nhộn 🧸', ageRange: '4-6 tuổi', icon: '🇻🇳', themeColor: '#8B5CF6', levels: [cL(1,"A","Nhớ chữ A","A","Đúng","Ă","Sai"), cL(2,"Ă","Nhớ chữ Ă","Ă","Đúng","Â","Sai"), cL(3,"Â","Nhớ chữ Â","Â","Đúng","A","Sai"), cL(4,"B","Nhớ chữ B","B","Đúng","C","Sai"), cL(5,"C","Nhớ chữ C","C","Đúng","B","Sai")] },
  { id: 'g54', category: 'Logic', title: 'Lật Hình Cặp Hình – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '👥', themeColor: '#8B5CF6', levels: [cL(1,"Sao","Cặp sao","⭐","⭐","🌙","🌙"), cL(2,"Tim","Cặp tim","❤️","❤️","💎","💎"), cL(3,"Mây","Cặp mây","☁️","☁️","☀️","☀️"), cL(4,"Cá","Cặp cá","🐟","🐟","🦀","🦀"), cL(5,"Bóng","Cặp bóng","⚽","⚽","🏀","🏀")] },
  { id: 'g55', category: 'Logic', title: 'Lật Hình Hình–Chữ – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🔤', themeColor: '#8B5CF6', levels: [cL(1,"Apple","Quả táo","🍎","Apple","🍌","Banana"), cL(2,"Dog","Con chó","🐶","Dog","🐱","Cat"), cL(3,"One","Số 1","1","One","2","Two"), cL(4,"Sun","Mặt trời","☀️","Sun","🌙","Moon"), cL(5,"Car","Ô tô","🚗","Car","🚲","Bike")] },
];

// --- NHÓM 5: GHÉP HÌNH (10 Game: g56 -> g65) ---
const PuzzleGames: GameDefinition[] = [
  { id: 'g56', category: 'Logic', title: 'Ghép Hình Con Vật – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🧩', themeColor: '#F59E0B', levels: [cL(1,"Phần đầu","Mảnh đầu của?","🐶","Chó","🐱","Mèo"), cL(2,"Đuôi","Mảnh đuôi của?","🐒","Khỉ","🐘","Voi"), cL(3,"Tai","Mảnh tai dài?","🐰","Thỏ","🐻","Gấu"), cL(4,"Vòi","Mảnh vòi dài?","🐘","Voi","🐍","Rắn"), cL(5,"Cổ","Mảnh cổ cao?","🦒","Hươu","🦓","Ngựa")] },
  { id: 'g57', category: 'Logic', title: 'Ghép Hình Hoa Quả – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🍍', themeColor: '#F59E0B', levels: [cL(1,"Vỏ","Mảnh vỏ cam","🍊","Cam","🍋","Chanh"), cL(2,"Hạt","Mảnh dưa hấu","🍉","Dưa","🍎","Táo"), cL(3,"Cuống","Mảnh cuống lê","🍐","Lê","🍑","Đào"), cL(4,"Lá","Mảnh lá dâu","🍓","Dâu","🍒","Ri"), cL(5,"Mảnh","Mảnh xoài vàng","🥭","Xoài","🥥","Dừa")] },
  { id: 'g58', category: 'Logic', title: 'Ghép Hình Đồ Chơi – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🧸', themeColor: '#F59E0B', levels: [cL(1,"Búp bê","Mảnh đầu búp bê","🪆","Đúng","🧸","Gấu"), cL(2,"Gấu bông","Mảnh tai gấu","🧸","Gấu","🤡","Hề"), cL(3,"Robot","Mảnh tay sắt","🤖","Robot","🚗","Xe"), cL(4,"Xếp hình","Mảnh lego","🧱","Lego","⚽","Bóng"), cL(5,"Bóng","Mảnh bóng tròn","⚽","Bóng","🎈","Bay")] },
  { id: 'g59', category: 'Logic', title: 'Ghép Hình Chữ Cái – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🔡', themeColor: '#F59E0B', levels: [cL(1,"Mảnh A","Mảnh chân chữ A","A","Đúng","H","Sai"), cL(2,"Mảnh O","Mảnh vòng tròn O","O","Đúng","U","Sai"), cL(3,"Mảnh T","Mảnh gạch ngang T","T","Đúng","L","Sai"), cL(4,"Mảnh X","Mảnh dấu chéo X","X","Đúng","K","Sai"), cL(5,"Mảnh S","Mảnh đường cong S","S","Đúng","Z","Sai")] },
  { id: 'g60', category: 'Logic', title: 'Ghép Hình Số – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🧩', themeColor: '#F59E0B', levels: [cL(1,"Mảnh 1","Mảnh gậy số 1","1","Đúng","7","Sai"), cL(2,"Mảnh 0","Mảnh trứng số 0","0","Đúng","8","Sai"), cL(3,"Mảnh 8","Mảnh hai vòng 8","8","Đúng","0","Sai"), cL(4,"Mảnh 4","Mảnh ghế số 4","4","Đúng","1","Sai"), cL(5,"Mảnh 7","Mảnh gậy số 7","7","Đúng","1","Sai")] },
  { id: 'g61', category: 'Logic', title: 'Ghép Hình Phương Tiện – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🚁', themeColor: '#F59E0B', levels: [cL(1,"Mảnh Xe","Mảnh bánh ô tô","🚗","Xe","✈️","Bay"), cL(2,"Mảnh Bay","Mảnh cánh máy bay","✈️","Bay","🚢","Tàu"), cL(3,"Mảnh Tàu","Mảnh ống khói tàu","🚢","Tàu","🚗","Xe"), cL(4,"Mảnh Đạp","Mảnh nan hoa xe","🚲","Đạp","🛵","Máy"), cL(5,"Mảnh Trực","Mảnh cánh quạt","🚁","Trực","🚂","Lửa")] },
  { id: 'g62', category: 'Logic', title: 'Ghép Hình Ngôi Nhà – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '🏘️', themeColor: '#F59E0B', levels: [cL(1,"Mảnh Mái","Mảnh mái nhà đỏ","🏠","Mái","🌳","Cây"), cL(2,"Mảnh Cửa","Mảnh cánh cửa sổ","🪟","Cửa","🚪","Chính"), cL(3,"Mảnh Vườn","Mảnh cỏ xanh","🌱","Cỏ","🧱","Tường"), cL(4,"Mảnh Ống","Mảnh ống khói","🏭","Khói","🏠","Nhà"), cL(5,"Mảnh Đèn","Mảnh đèn lồng","🏮","Đèn","🏠","Nhà")] },
  { id: 'g63', category: 'Logic', title: 'Ghép Hình Khuôn Mặt – Level Vui Nhộn 🧸', ageRange: '3-6 tuổi', icon: '😊', themeColor: '#F59E0B', levels: [cL(1,"Mảnh Mắt","Mảnh mắt long lanh","👀","Mắt","👃","Mũi"), cL(2,"Mảnh Môi","Mảnh miệng cười","👄","Cười","👂","Tai"), cL(3,"Mảnh Tóc","Mảnh tóc mây","💇","Tóc","👕","Áo"), cL(4,"Mảnh Tai","Mảnh tai nghe","👂","Tai","👀","Mắt"), cL(5,"Mảnh Mũi","Mảnh mũi dọc dừa","👃","Mũi","👄","Môi")] },
  { id: 'g64', category: 'Logic', title: 'Ghép Hình Bóng Đổ – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🌑', themeColor: '#F59E0B', levels: [cL(1,"Bóng Táo","Bóng này là của? 🌑","🍎","Táo","🍌","Chuối"), cL(2,"Bóng Chó","Bóng này là của? 🌑","🐶","Chó","🐱","Mèo"), cL(3,"Bóng Xe","Bóng này là của? 🌑","🚗","Xe","🚲","Đạp"), cL(4,"Bóng Bay","Bóng này là của? 🌑","✈️","Bay","🚢","Tàu"), cL(5,"Bóng Nhà","Bóng này là của? 🌑","🏠","Nhà","🌳","Cây")] },
  { id: 'g65', category: 'Logic', title: 'Ghép Hình Nâng Cao – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '👑', themeColor: '#F59E0B', levels: [cL(1,"Lâu đài","Mảnh tháp cao","🏰","Lâu đài","🏠","Nhà"), cL(2,"Vũ trụ","Mảnh hành tinh","🪐","Vũ trụ","☀️","Nắng"), cL(3,"Rừng","Mảnh hổ gầm","🐯","Hổ","🐱","Mèo"), cL(4,"Biển","Mảnh cá voi","🐋","Cá voi","🐟","Cá con"), cL(5,"Thành phố","Mảnh nhà cao tầng","🏙️","Thành phố","🌳","Rừng")] },
];

// --- NHÓM 6: GHÉP CHỮ VN (10 Game: g66 -> g75) ---
const SpellingGames: GameDefinition[] = [
  { id: 'g66', category: 'Vietnamese', title: 'Ghép Chữ Thành Từ VN – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '📝', themeColor: '#EF4444', levels: [cL(1,"Cá","Ghép C-Á","Á","CÁ","A","CA"), cL(2,"Gà","Ghép G-À","À","GÀ","A","GA"), cL(3,"Bò","Ghép B-Ò","Ò","BÒ","O","BO"), cL(4,"Dê","Ghép D-Ê","Ê","DÊ","E","DE"), cL(5,"Hổ","Ghép H-Ổ","Ổ","HỔ","O","HO")] },
  { id: 'g67', category: 'Vietnamese', title: 'Ghép Chữ Theo Hình – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🖼️', themeColor: '#EF4444', levels: [cL(1,"Táo","Hình 🍎 ghép gì?","Táo","Táo","Cam","Cam"), cL(2,"Nho","Hình 🍇 ghép gì?","Nho","Nho","Lê","Lê"), cL(3,"Mèo","Hình 🐱 ghép gì?","Mèo","Mèo","Chó","Chó"), cL(4,"Hoa","Hình 🌸 ghép gì?","Hoa","Hoa","Lá","Lá"), cL(5,"Cá","Hình 🐟 ghép gì?","Cá","Cá","Bò","Bò")] },
  { id: 'g68', category: 'Vietnamese', title: 'Ghép Chữ Thiếu – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '✍️', themeColor: '#EF4444', levels: [cL(1,"Học","H-?-C","O","Học","A","Hạc"), cL(2,"Mẹ","M-?","Ẹ","Mẹ","E","Me"), cL(3,"Ba","B-?","A","Ba","O","Bo"), cL(4,"Cá","C-?","Á","Cá","A","Ca"), cL(5,"Gà","G-?","À","Gà","A","Ga")] },
  { id: 'g69', category: 'Vietnamese', title: 'Ghép Chữ Đúng Thứ Tự – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '📏', themeColor: '#EF4444', levels: [cL(1,"BÉ","B-É hay É-B?","BÉ","Đúng","ÉB","Sai"), cL(2,"MẸ","M-Ẹ hay Ẹ-M?","MẸ","Đúng","ẸM","Sai"), cL(3,"HỌC","H-O-C hay C-O-H?","HỌC","Đúng","COH","Sai"), cL(4,"CÁ","C-Á hay Á-C?","CÁ","Đúng","ÁC","Sai"), cL(5,"NHÀ","N-H-À hay À-H-N?","NHÀ","Đúng","ÀHN","Sai")] },
  { id: 'g70', category: 'Vietnamese', title: 'Ghép Chữ Con Vật – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🐾', themeColor: '#EF4444', levels: [cL(1,"Vịt","V-Ị-T","Vịt","Vịt","Gà","Gà"), cL(2,"Heo","H-E-O","Heo","Heo","Bò","Bò"), cL(3,"Voi","V-O-I","Voi","Voi","Hổ","Hổ"), cL(4,"Rùa","R-Ù-A","Rùa","Rùa","Cá","Cá"), cL(5,"Khỉ","K-H-Ỉ","Khỉ","Khỉ","Dê","Dê")] },
  { id: 'g71', category: 'Vietnamese', title: 'Ghép Chữ Hoa Quả – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🍓', themeColor: '#EF4444', levels: [cL(1,"Mận","M-Ậ-N","Mận","Mận","Đào","Đào"), cL(2,"Đào","Đ-À-O","Đào","Đào","Lê","Lê"), cL(3,"Lê","L-Ê","Lê","Lê","Dâu","Dâu"), cL(4,"Dâu","D-Â-U","Dâu","Dâu","Cam","Cam"), cL(5,"Cam","C-A-M","Cam","Cam","Quýt","Quýt")] },
  { id: 'g72', category: 'Vietnamese', title: 'Ghép Chữ Màu Sắc – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🎨', themeColor: '#EF4444', levels: [cL(1,"Đỏ","Đ-Ỏ","Đỏ","Đỏ","Xanh","Xanh"), cL(2,"Xanh","X-A-N-H","Xanh","Xanh","Đỏ","Đỏ"), cL(3,"Vàng","V-À-N-G","Vàng","Vàng","Tím","Tím"), cL(4,"Tím","T-Í-M","Tím","Tím","Nâu","Nâu"), cL(5,"Nâu","N-Â-U","Nâu","Nâu","Đen","Đen")] },
  { id: 'g73', category: 'Vietnamese', title: 'Ghép Chữ Đồ Vật – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🎒', themeColor: '#EF4444', levels: [cL(1,"Bàn","B-À-N","Bàn","Bàn","Ghế","Ghế"), cL(2,"Ghế","G-H-Ê-Sắc","Ghế","Ghế","Bàn","Bàn"), cL(3,"Tủ","T-Ủ","Tủ","Tủ","Giường","Giường"), cL(4,"Sách","S-Á-C-H","Sách","Sách","Vở","Vở"), cL(5,"Vở","V-Ở","Vở","Vở","Bút","Bút")] },
  { id: 'g74', category: 'Vietnamese', title: 'Ghép Chữ Nâng Cao – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '🚀', themeColor: '#EF4444', levels: [cL(1,"Trường","T-R-Ư-Ờ-N-G","Trường","Trường","Lớp","Lớp"), cL(2,"Thầy","T-H-Ầ-Y","Thầy","Thầy","Cô","Cô"), cL(3,"Bạn","B-Ạ-N","Bạn","Bạn","Tôi","Tôi"), cL(4,"Ngoan","N-G-O-A-N","Ngoan","Ngoan","Hư","Hư"), cL(5,"Giỏi","G-I-Ỏ-I","Giỏi","Giỏi","Khá","Khá")] },
  { id: 'g75', category: 'Vietnamese', title: 'Ghép Câu Đơn Giản – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '🖋️', themeColor: '#EF4444', levels: [cL(1,"Bé đi học","Ghép câu","Bé đi học","Đúng","Học đi bé","Sai"), cL(2,"Mẹ yêu con","Ghép câu","Mẹ yêu con","Đúng","Con yêu mẹ","Sai"), cL(3,"Em là bé ngoan","Ghép câu","Em là bé ngoan","Đúng","Bé ngoan là em","Sai"), cL(4,"Cây xanh lá","Ghép câu","Cây xanh lá","Đúng","Lá xanh cây","Sai"), cL(5,"Bầu trời xanh","Ghép câu","Bầu trời xanh","Đúng","Xanh trời bầu","Sai")] },
];

// --- NHÓM 7: TÌM KHÁC BIỆT (10 Game: g76 -> g85) ---
const DifferenceGames: GameDefinition[] = [
  { id: 'g76', category: 'Logic', title: 'Khác Biệt Con Vật – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🔍', themeColor: '#10B981', levels: [cL(1,"Màu sắc","Con nào khác màu?","🐯","Khác","🐱","Giống"), cL(2,"Kích thước","Con nào to nhất?","🐘","Voi","🐭","Chuột"), cL(3,"Số lượng","Nhóm nào nhiều cá hơn?","🐟🐟🐟","3 con","🐟","1 con"), cL(4,"Hành động","Bạn nào đang bay?","🕊️","Đang bay","🐕","Đang chạy"), cL(5,"Nơi sống","Ai không ở dưới nước?","🐶","Chó","🐳","Cá voi")] },
  { id: 'g77', category: 'Logic', title: 'Khác Biệt Hoa Quả – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🍓', themeColor: '#10B981', levels: [cL(1,"Loại quả","Quả nào khác loại?","🍌","Dài","🍎","Tròn"), cL(2,"Màu","Quả nào không đỏ?","🍐","Xanh","🍎","Đỏ"), cL(3,"Vị","Quả nào chua nhất?","🍋","Chanh","🍉","Dưa hấu"), cL(4,"Hạt","Quả nào nhiều hạt?","🐉","Thanh long","🥭","Xoài"), cL(5,"Vỏ","Quả nào vỏ gai?","🍍","Dứa","🍎","Táo")] },
  { id: 'g78', category: 'Logic', title: 'Khác Biệt Phòng Ngủ – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🛏️', themeColor: '#10B981', levels: [cL(1,"Đồ vật","Phòng nào có robot?","🤖","Có","🧸","Không"), cL(2,"Màu gối","Gối nào màu xanh?","🔵","Xanh","🔴","Đỏ"), cL(3,"Vị trí","Gấu ở trên giường?","Trên","Đúng","Dưới","Sai"), cL(4,"Ánh sáng","Đèn nào đang bật?","💡","Sáng","🌑","Tắt"), cL(5,"Sách","Phòng nào nhiều sách?","📚","Nhiều","📖","Ít")] },
  { id: 'g79', category: 'Logic', title: 'Khác Biệt Khu Vườn – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🌳', themeColor: '#10B981', levels: [cL(1,"Hoa","Bông hoa nào khác màu?","🌻","Vàng","🌹","Đỏ"), cL(2,"Cây","Cây nào cao nhất?","🌳","Cao","🌱","Thấp"), cL(3,"Côn trùng","Bạn nào có cánh?","🦋","Bướm","🐛","Sâu"), cL(4,"Bầu trời","Vườn nào có nắng?","☀️","Nắng","🌧️","Mưa"), cL(5,"Chim","Vườn nào có chim?","🐦","Có","🐱","Không")] },
  { id: 'g80', category: 'Logic', title: 'Khác Biệt Màu Sắc – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🎨', themeColor: '#10B981', levels: [cL(1,"Đỏ","Tìm màu đỏ","🔴","Đỏ","🔵","Xanh"), cL(2,"Nhạt","Màu nào nhạt hơn?","⚪","Nhạt","⚫","Đậm"), cL(3,"Nóng","Màu nào ấm áp?","🔥","Cam","❄️","Xanh"), cL(4,"Cầu vồng","Màu nào trong cầu vồng?","🌈","Đúng","⬛","Không"), cL(5,"Trộn","Đỏ + Vàng = ?","🟠","Cam","🟢","Lá")] },
  { id: 'g81', category: 'Logic', title: 'Tìm Hình Thiếu Chi Tiết – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🧩', themeColor: '#10B981', levels: [cL(1,"Xe","Xe thiếu bánh nào?","Wheel","Bánh","Door","Cửa"), cL(2,"Mặt","Khuôn mặt thiếu gì?","👀","Mắt","👃","Mũi"), cL(3,"Nhà","Nhà thiếu cái gì?","🏠","Mái","🌳","Cây"), cL(4,"Thỏ","Thỏ thiếu cái gì?","👂","Tai","🦶","Chân"), cL(5,"Cây","Cây thiếu cái gì?","🍃","Lá","🍎","Quả")] },
  { id: 'g82', category: 'Logic', title: 'Tìm Hình Sai Màu – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🖍️', themeColor: '#10B981', levels: [cL(1,"Chuối","Chuối màu gì sai?","🔴","Đỏ","🟡","Vàng"), cL(2,"Bầu trời","Trời màu gì sai?","🟢","Lá","🔵","Xanh"), cL(3,"Lá","Lá màu gì sai?","🟣","Tím","🟢","Lá"), cL(4,"Táo","Táo màu gì sai?","🔵","Xanh","🍎","Đỏ"), cL(5,"Lợn","Lợn màu gì sai?","⬛","Đen","🌸","Hồng")] },
  { id: 'g83', category: 'Logic', title: 'Tìm Hình Khác Loại – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🚫', themeColor: '#10B981', levels: [cL(1,"Ăn","Cái nào không ăn được?","🧱","Gạch","🍰","Bánh"), cL(2,"Mặc","Cái nào không để mặc?","🥣","Bát","👕","Áo"), cL(3,"Đi học","Đồ nào không đi học?","🧸","Gấu","🎒","Cặp"), cL(4,"Bay","Con nào không bay?","🐕","Chó","🐦","Chim"), cL(5,"Nước","Con nào không dưới nước?","🐱","Mèo","🐟","Cá")] },
  { id: 'g84', category: 'Logic', title: 'Tìm Chi Tiết Không Đúng – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '⚠️', themeColor: '#10B981', levels: [cL(1,"Cá","Cá có cánh không?","Không","Đúng","Có","Sai"), cL(2,"Chim","Chim có vây không?","Không","Đúng","Có","Sai"), cL(3,"Voi","Voi có nhỏ không?","Không","Đúng","Có","Sai"), cL(4,"Lửa","Lửa có lạnh không?","Không","Đúng","Có","Sai"), cL(5,"Kem","Kem có nóng không?","Không","Đúng","Có","Sai")] },
  { id: 'g85', category: 'Logic', title: 'Khác Biệt Nâng Cao – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '🕵️', themeColor: '#10B981', levels: [cL(1,"Mê cung","Đường nào đúng?","A","Đúng","B","Sai"), cL(2,"Số","Số nào to nhất?","100","Đúng","10","Sai"), cL(3,"Chữ","Chữ nào viết sai?","Scool","Sai","School","Đúng"), cL(4,"Hình","Hình nào 5 cạnh?","Pentagon","5 cạnh","Square","4 cạnh"), cL(5,"Logic","1+1+1=?","3","Đúng","2","Sai")] },
];

// --- NHÓM 8: PHÂN LOẠI (10 Game: g86 -> g95) ---
const ClassifyGames: GameDefinition[] = [
  { id: 'g86', category: 'Logic', title: 'Chọn KHÔNG PHẢI Chữ – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🅰️', themeColor: '#EC4899', levels: [cL(1,"Số","Đâu không là chữ? A, B, 1","1","Số 1","A","Chữ A"), cL(2,"Hình","Đâu không là chữ? C, D, ⭕","⭕","Hình tròn","C","Chữ C"), cL(3,"Vật","Đâu không là chữ? E, F, 🍎","🍎","Quả táo","E","Chữ E"), cL(4,"Số","Đâu không là chữ? G, H, 5","5","Số 5","G","Chữ G"), cL(5,"Vật","Đâu không là chữ? K, L, 🚗","🚗","Ô tô","K","Chữ K")] },
  { id: 'g87', category: 'Logic', title: 'Chọn KHÔNG ĐÚNG Số – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🔢', themeColor: '#EC4899', levels: [cL(1,"Chữ","Đâu không là số? 1, 2, A","A","Chữ A","1","Số 1"), cL(2,"Vật","Đâu không là số? 3, 4, 🐱","🐱","Con mèo","3","Số 3"), cL(3,"Chữ","Đâu không là số? 5, 6, B","B","Chữ B","5","Số 5"), cL(4,"Hình","Đâu không là số? 7, 8, ⭐","⭐","Ngôi sao","7","Số 7"), cL(5,"Vật","Đâu không là số? 9, 0, 🎒","🎒","Cái cặp","9","Số 9")] },
  { id: 'g88', category: 'Logic', title: 'Chọn KHÔNG PHẢI Quả – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🍎', themeColor: '#EC4899', levels: [cL(1,"Vật","Đâu không là quả? 🍎, 🍌, 🔨","🔨","Cái búa","🍎","Quả táo"), cL(2,"Vật","Đâu không là quả? 🍇, 🍓, 👟","👟","Chiếc giày","🍇","Chùm nho"), cL(3,"Con","Đâu không là quả? 🍉, 🥭, 🐶","🐶","Con chó","🍉","Dưa hấu"), cL(4,"Số","Đâu không là quả? 🍐, 🍒, 9","9","Số 9","🍐","Quả lê"), cL(5,"Hình","Đâu không là quả? 🥥, 🍍, 🔺","🔺","Tam giác","🥥","Quả dừa")] },
  { id: 'g89', category: 'Logic', title: 'Chọn KHÔNG Cùng Nhóm – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🐾', themeColor: '#EC4899', levels: [cL(1,"Bay","Ai không biết bay? 🦅, 🦜, 🐘","🐘","Con voi","🦅","Đại bàng"), cL(2,"Bơi","Ai không dưới nước? 🐟, 🐙, 🐱","🐱","Con mèo","🐟","Con cá"), cL(3,"Rừng","Ai không ở rừng? 🦁, 🐯, 🐷","🐷","Con lợn","🦁","Sư tử"), cL(4,"Nhà","Ai không nuôi ở nhà? 🐶, 🐱, 🦖","🦖","Khủng long","🐶","Con chó"), cL(5,"Lớn","Ai không to lớn? 🐘, 🐋, 🐜","🐜","Con kiến","🐘","Con voi")] },
  { id: 'g90', category: 'Logic', title: 'Chọn KHÔNG GIỐNG Màu – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🔴', themeColor: '#EC4899', levels: [cL(1,"Đỏ","Ai không màu đỏ? 🍎, 🍓, 🍌","🍌","Màu vàng","🍎","Màu đỏ"), cL(2,"Xanh","Ai không xanh lá? 🍃, 🥦, 🥕","🥕","Màu cam","🍃","Xanh lá"), cL(3,"Vàng","Ai không màu vàng? 🍋, 🌽, 🍆","🍆","Màu tím","🍋","Màu vàng"), cL(4,"Xanh dương","Ai không xanh dương? 🌊, 🐋, ☀️","☀️","Màu vàng","🌊","Xanh dương"), cL(5,"Trắng","Ai không màu trắng? 🥛, 🥚, 🍫","🍫","Màu nâu","🥛","Màu trắng")] },
  { id: 'g91', category: 'Logic', title: 'Chọn KHÔNG Cùng Hình – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '⭕', themeColor: '#EC4899', levels: [cL(1,"Tròn","Ai không hình tròn? ⚽, 🍩, 📦","📦","Hình hộp","⚽","Hình tròn"), cL(2,"Vuông","Ai không hình vuông? 📦, 🪟, ⚽","⚽","Hình tròn","📦","Hình vuông"), cL(3,"Dài","Ai không dài? 🥖, 🥒, 🍪","🍪","Hình tròn","🥖","Dài"), cL(4,"Nhọn","Ai không có đỉnh? 🔺, ⭐, ⭕","⭕","Hình tròn","🔺","Tam giác"), cL(5,"Phẳng","Ai không phẳng? 📄, 🖼️, ⚽","⚽","Khối cầu","📄","Tờ giấy")] },
  { id: 'g92', category: 'Logic', title: 'Chọn KHÔNG TRONG Nhà – Level Vui Nhộn 🧸', ageRange: '4-7 tuổi', icon: '🏠', themeColor: '#EC4899', levels: [cL(1,"Đồ","Đồ nào không trong nhà? 🛋️, 🛏️, ✈️","✈️","Máy bay","🛋️","Ghế sofa"), cL(2,"Vật","Đồ nào không ở bếp? 🥣, 🍳, 🛏️","🛏️","Cái giường","🥣","Cái bát"), cL(3,"Phòng","Đồ nào không ở tắm? 🛀, 🧼, 🍳","🍳","Cái chảo","🛀","Bồn tắm"), cL(4,"Sân","Đồ nào không ở sân? 🌳, 🚲, 📺","📺","Tivi","🌳","Cái cây"), cL(5,"Ngoại","Đồ nào ngoài đường? 🚗, 🚥, 🛋️","🛋️","Ghế sofa","🚗","Ô tô")] },
  { id: 'g93', category: 'Logic', title: 'Chọn CHỮ SAI Chính Tả – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '❌', themeColor: '#EC4899', levels: [cL(1,"Học","Học hay Hục?","Hục","Sai","Học","Đúng"), cL(2,"Bé","Bé hay Bế? (tên gọi)","Bế","Sai","Bé","Đúng"), cL(3,"Cá","Cá hay Cà? (con vật)","Cà","Sai","Cá","Đúng"), cL(4,"Gà","Gà hay Gá? (con vật)","Gá","Sai","Gà","Đúng"), cL(5,"Bà","Bà hay Bá? (người thân)","Bá","Sai","Bà","Đúng")] },
  { id: 'g94', category: 'Logic', title: 'Chọn KHÔNG LIÊN QUAN – Level Vui Nhộn 🧸', ageRange: '5-7 tuổi', icon: '🧩', themeColor: '#EC4899', levels: [cL(1,"Mưa","Mưa thì cần gì?","🌂","Ô","🕶️","Kính"), cL(2,"Học","Đi học cần gì?","🎒","Cặp","🥣","Bát"), cL(3,"Tắm","Tắm cần gì?","🧼","Xà phòng","⚽","Bóng"), cL(4,"Ngủ","Đi ngủ cần gì?","🛌","Giường","🚲","Xe đạp"), cL(5,"Ăn","Ăn cơm cần gì?","🥢","Đũa","🖍️","Bút")] },
  { id: 'g95', category: 'Logic', title: 'Thử Thách Tổng Hợp 🏆 – Level Vui Nhộn 🧸', ageRange: '6-7 tuổi', icon: '🥇', themeColor: '#EC4899', levels: [cL(1,"IQ","1+1+1=?","3","Đúng","2","Sai"), cL(2,"Màu","Đỏ + Xanh dương = ?","🟣","Tím","🟢","Xanh lá"), cL(3,"Từ","Quả gì tên bắt đầu bằng T?","Táo","Đúng","Cam","Sai"), cL(4,"Con","Con gì gáy sáng?","🐓","Gà trống","🐥","Gà con"), cL(5,"Bé","Bé thông minh không?","Có","Rất giỏi","Không","Sai rồi")] },
];

// --- NHÓM 9: TƯ DUY TỔNG HỢP (5 Game: g96 -> g100) ---
const ExtraLogicGames: GameDefinition[] = [
  { id: 'g96', category: 'Logic', title: 'Bé Học Màu Cơ Bản – Level Vui Nhộn 🧸', ageRange: '2-3 tuổi', icon: '🔴', themeColor: '#8B5CF6', levels: [cL(1,"Đỏ","Tìm Đỏ","🔴","Đỏ","🔵","Xanh"), cL(2,"Xanh","Tìm Xanh","🔵","Xanh","🟡","Vàng"), cL(3,"Vàng","Tìm Vàng","🟡","Vàng","🟢","Lá"), cL(4,"Lá","Tìm Lá","🟢","Lá","🔴","Đỏ"), cL(5,"Tất cả","Đẹp không?","🌈","Đẹp","⬛","Xấu")] },
  { id: 'g97', category: 'Logic', title: 'Bé Nhận Biết Hình Khối – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '💠', themeColor: '#8B5CF6', levels: [cL(1,"Tròn","Hình tròn","⭕","Tròn","⬜","Vuông"), cL(2,"Vuông","Hình vuông","⬜","Vuông","🔺","Tam giác"), cL(3,"Tam giác","Hình tam giác","🔺","Tam giác","⭐","Sao"), cL(4,"Sao","Ngôi sao","⭐","Sao","⭕","Tròn"), cL(5,"Tim","Trái tim","❤️","Tim","⬜","Vuông")] },
  { id: 'g98', category: 'Logic', title: 'Giống Hay Khác? – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🎭', themeColor: '#8B5CF6', levels: [cL(1,"Giống","Cặp nào giống?","🍎🍎","Giống","🍎🍌","Khác"), cL(2,"Khác","Cặp nào khác?","🐶🐱","Khác","🐱🐱","Giống"), cL(3,"Giống","Cặp nào giống?","⭐⭐","Giống","⭐🌙","Khác"), cL(4,"Khác","Cặp nào khác?","🔴🔵","Khác","🔴🔴","Giống"), cL(5,"Giống","Cặp nào giống?","A A","Giống","A B","Khác")] },
  { id: 'g99', category: 'Logic', title: 'Cao Hay Thấp? – Level Vui Nhộn 🧸', ageRange: '3-5 tuổi', icon: '🦒', themeColor: '#8B5CF6', levels: [cL(1,"Cao","Bạn nào cao?","🦒","Hươu","🐕","Chó"), cL(2,"Thấp","Bạn nào thấp?","🐜","Kiến","🐘","Voi"), cL(3,"Cao","Cái nào cao?","🌳","Cây","🌱","Cỏ"), cL(4,"Thấp","Cái nào thấp?","🏠","Nhà","🏙️","Tòa nhà"), cL(5,"Cao","Ai cao nhất?","Giraffe","Hươu","Cat","Mèo")] },
  { id: 'g100', category: 'Logic', title: 'To Hay Nhỏ? – Level Vui Nhộn 🧸', ageRange: '2-4 tuổi', icon: '🐋', themeColor: '#8B5CF6', levels: [cL(1,"To","Con nào to?","🐘","Voi","🐭","Chuột"), cL(2,"Nhỏ","Con nào nhỏ?","🐥","Gà con","🐄","Bò tót"), cL(3,"To","Cái nào to?","🚚","Xe tải","🚲","Xe đạp"), cL(4,"Nhỏ","Cái nào nhỏ?","🍬","Kẹo","🍉","Dưa hấu"), cL(5,"To","Ai to nhất?","🐋","Cá voi","🐟","Cá con")] },
];

/**
 * TỔNG HỢP CHÍNH XÁC 100 GAME
 */
export const ROADMAP: GameDefinition[] = [
  ...EnglishGames,    // 15 (g1-g15)
  ...MathGames,       // 15 (g16-g30)
  ...VietnameseGames, // 15 (g31-g45)
  ...MemoryGames,     // 10 (g46-g55)
  ...PuzzleGames,     // 10 (g56-g65)
  ...SpellingGames,   // 10 (g66-g75)
  ...DifferenceGames, // 10 (g76-g85)
  ...ClassifyGames,   // 10 (g86-g95)
  ...ExtraLogicGames  // 5  (g96-g100)
];
